import type { Metadata } from "next";
import "./globals.css";
import { Inter,Noto_Serif } from "next/font/google";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const notoserif = Noto_Serif({ subsets: ["latin"], variable: "--font-notoserif" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${notoserif.variable} ${inter.variable} h-full antialiased`}
    >
      <body className={`${inter.className} min-h-full flex flex-col`}>
        {children}
        <Toaster duration={3000} position="top-center"  toastOptions={{style:{background:'#422521',borderStyle:'solid',borderColor:'#81392B',color:'white'}}}/>
      </body>
    </html>
  );
}
